name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    env:
      SELENIUM_URL: http://0.0.0.0:4444/wd/hub
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.63.0
        with: 
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
                    
      - name: Install Yarn
        run: yarn install
                                
      - name: Prepare Database
        run: bundle exec rails db:prepare

      - name: Run Tests
        run: RAILS_ENV=test bundle exec rails test:system
                
  ping_rails_new_io:
    name: Ping ping railsnew.io after CI finished
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: echo "REPO_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "$REPOSITORY_NAME"
        shell: bash    
        
      - uses: technote-space/workflow-conclusion-action@v2
      
      - name: ping Railsnew.io
        uses: fjogeleit/http-request-action@master
        with:
          url: "http://ecb72f5b9f65.ngrok.io/admin/verification_runs/${{env.REPO_NAME}}?github_status=${{ env.WORKFLOW_CONCLUSION }}"
          method: 'PUT'
          bearerToken: ${{ secrets.RAILS_NEW_IO_TOKEN }}        
